const ChildrenDetails = [
    {
        id: 1,
        name: 'Aarav',
        age: 8,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '1',
      },
      {
        id: 2,
        name: 'Aanya',
        age: 6,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '2',
      },
      {
        id: 3,
        name: 'Advait',
        age: 10,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '3',
      },
      {
        id: 4,
        name: 'Aishwarya',
        age: 7,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '1',
      },
      {
        id: 5,
        name: 'Aarush',
        age: 9,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '2',
      },
      {
        id: 6,
        name: 'Ananya',
        age: 5,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '3',
      },
      {
        id: 7,
        name: 'Ayaan',
        age: 8,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '1',
      },
      {
        id: 8,
        name: 'Aaradhya',
        age: 6,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '2',
      },
      {
        id: 9,
        name: 'Arjun',
        age: 7,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '3',
      },
      {
        id: 10,
        name: 'Avni',
        age: 9,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '1',
      },
      {
        id: 11,
        name: 'Aryan',
        age: 6,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '2',
      },
      {
        id: 12,
        name: 'Anika',
        age: 8,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '3',
      },
      {
        id: 13,
        name: 'Ayaan',
        age: 10,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '1',
      },
      {
        id: 14,
        name: 'Mia',
        age: 7,
        location: 'Maharashtra',
        photo: 'https://fastly.picsum.photos/id/22/4434/3729.jpg?hmac=fjZdkSMZJNFgsoDh8Qo5zdA_nSGUAWvKLyyqmEt2xs0',
        stage: '2',
      }
];

export default ChildrenDetails;
